language: php

php:
  - 5.6.6
  - 5.6.7
  - 5.6.8
  - 5.6.9
  - 5.6.10
  - 5.6.11
  - 5.6.12
  - 5.6.13
  - 5.6.14
  - 5.6.15
  - 5.6.16
  - 5.6.17
  - 5.6.18
  - 5.6.19
  - 5.6.20
  - 5.6.21
  - 5.6.22
  - 5.6.23
  - 5.6.24
  - 5.6.25
  - 5.6.26
  - 5.6.27
  - 5.6.28
  - 5.6.29
  - 5.6.30
  - 5.6.31
  - 5.6.32
  - 5.6.33
  - 5.6.34
  - 5.6.35
  - 5.6.36
  - 5.6.37
  - 5.6.38
  - 5.6.39
  - 5.6.40
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit tests/ESTest
